name: CI
on:
  pull_request:
    types: [edited, opened, reopened, synchronize]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - run: npm i
      - name: Download test case file
        run: |
          curl -f -o tests/test-case-private.test.js 'https://work-flow-bucket-3.s3.us-east-1.amazonaws.com/post_hidden.test.js?response-content-disposition=inline&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEOL%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLWVhc3QtMSJHMEUCIQDdyaWYPva%2FTpHAh5CDq7ESxT0tp%2BLzEvvDbeyakCN%2B0wIgNZBmIssZDkd7xGEw68G1KjYnxqznffRTnjgcqHlxthcq1AQIm%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARAAGgw4MTc5MDEyMTIyMTciDE7e6f0Ttm%2FEgGyrrSqoBPs4kHtmRmSzRgrV%2FzbatZlbH73clelmr8ptfIbkAFIywWqftq1YPTYuXOXZpLS1cPR1l3BRep5DRLnZ02uGOMJ8woIZN8mQV7%2FZQryknGEcZSBfv%2BAfmwjRkCK7GdxjR3YN3bwIGo%2BIhSEOuVKNJCSQ86cl8XlQZ%2B1l3vDgTFBUoqHQpSI327EZRY93dbhB4LI6EoTqXZCDTzXpFY5JFizSZF7onzq%2BwpEw2WDOYTCzLgGpP9%2Bq8qh1yGRagjUpFJ5f8Tpo2qDYWNqpIIPNHLB%2FP3yK0nERJPSf5ynQJY02OQ3aBTAo%2BWt952WVp%2Fg4%2BfvcAl8L%2BixtsFWMz4Hn%2B7ReaiCwuEDFmGGn5jaiyjWZw0P3tjHpWsvtEb5OON9a46cZ0GybkakA0140vtsLBMkU5dVYzuTggPhb5yyTTeiNf6KvI9Zw20A5nJqxLxcrJUQgT5ntyBaPFoDAnjcKiYzQyzblcEsDaMNItzbVUxTNh1kOJOG4vVyb03EMzWEu%2FNdCazrTfgf1jLnH0Qk0ROc7SUvQP1OTw%2BLuHWbhYGQeql4pgEvF8inRZPJQ5zxbjaEt6jP6FBAMwrOPCX5zFwcVoC2TFI7Prjiw0AlcSP9G%2F%2FS9MNZcPtFdOKh9oJlrf%2Fb7TZGoAnp3p%2B0VmrNQtgKj1nVCCFpB15IftEbXZwZD9GnuGJaw0HVnNDBw9%2BjGBLTJIuG0w4obdbnA1Z4WeScx6GylriZMLzCcuK%2FBBjrFAjU7Ju%2B3H%2FZrLv%2BxrpaCNaktiu2cZzmJKyZrAeqeOOEURFg%2FgXwlGbAfU%2B7o1GBjjnpPe1LDR%2BSmDtjCGagTEXztHMIuvDr9Uhq98VMIjsloLsuB3lqKNpD4lylLlPfSgKMou4h%2Ff19%2FH3JzgDiTIM%2BBx4FnDs8HMNm6QtNau8ZEeYUSb7bEiRdea1OyE%2FpmJmn4qOwEpcmF2vp8hWs3sDFqdoWoDOccyX%2B1tKoFY1LlbkKDHg4Rj2jxJ7X9l%2F%2Fs2rPCDDG1zn3sXGaiAfOqS0zCtC1p5js%2F07aLzvLtsc2XZDEGxg0k7AR7wQ9DMTdT8D1pbVE8LCrG6P6F4oIl7yV0h2xrqCR%2BkS1uprglxyXA5xfKnWU%2ByabrMpcn8nSwguoZm26kE1I77p%2BAAHe7ZM1SasDgaTdFOJEhaoebt4bDeIn9bxI%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ASIA343VWCI43S6PPKJV%2F20250520%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250520T013857Z&X-Amz-Expires=43200&X-Amz-SignedHeaders=host&X-Amz-Signature=b3752a60285d1ce77a1bba8046d55663b350f08622fa671ccf25b5f54483a310'
      - name: Run tests and output JSON only
        # Pass Jest’s flags so that it writes pure JSON into the file,
        # without any extra console output.
        run: npm run unit -- --json --outputFile=test-results.json
        continue-on-error: true
      - name: Parse test results
        id: parse_results
        run: |
          passed=$(jq '.numPassedTests' test-results.json)
          total=$(jq '.numTotalTests' test-results.json)
          score="$passed/$total"
          echo "score=$score" >> $GITHUB_OUTPUT
      - name: Update Supabase
        run: |
          payload=$(echo '{}' | jq --arg score "${{ steps.parse_results.outputs.score }}" '.score = $score')
          curl -X PATCH "https://xuzpvjqeospaevrhekkg.supabase.co/rest/v1/assessment_applications?pr_number=eq.${{ github.event.pull_request.number }}" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_API_KEY }}" \
            -H "Content-Type: application/json" \
            -H "Prefer: return=representation" \
            -d "$payload"
