name: CI

on:
  pull_request:
    types: [edited, opened, reopened, synchronize]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Download test case file
        run: |
          curl -f -o tests/test-case-private.test.js 'https://work-flow-bucket-3.s3.us-east-1.amazonaws.com/post_hidden.test.js?response-content-disposition=inline&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Security-Token=…'

      - name: Run tests and output JSON only
        # Pass Jest’s flags so that it writes pure JSON into the file,
        # without any extra console output.
        run: npm run unit -- --json --outputFile=test-results.json
        continue-on-error: true

      - name: Parse test results
        id: parse_results
        run: |
          passed=$(jq '.numPassedTests' test-results.json)
          total=$(jq '.numTotalTests'  test-results.json)
          score="$passed/$total"
          echo "score=$score" >> $GITHUB_OUTPUT

      - name: Update Supabase
        run: |
          payload=$(jq -n --arg score "${{ steps.parse_results.outputs.score }}" '{score: $score}')
          curl -X PATCH "https://xuzpvjqeospaevrhekkg.supabase.co/rest/v1/assessment_applications?pr_number=eq.${{ github.event.pull_request.number }}" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_API_KEY }}" \
            -H "Content-Type: application/json" \
            -H "Prefer: return=representation" \
            -d "$payload"
