name: CI
on:
  pull_request:
    types: [edited, opened, reopened, synchronize]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn test
